#meta_by_ancestry_5pc_diff_dens.R

#Meta-analysis done for each ancestry group to generate ancestry sprecific summary stats for PAINTOR trans ethnic analysis

extension="final_collection"

#Readin family results as generated by Cassie:
cassiedir<-"/nv/vol185/MEGA/release4/IMPUTED_TOPMED/family_analysis/"
cohorts1=c("EAS","AFR","EUR","AMR", "FIN")
cohorts=c("AFR","EUR","AMR", "FIN")
progdir<-paste0("~/programs/",extension,"/META/")
resdir<-paste0("/scratch/ji3x/",extension,"_gwas/META/META/")


#now generate a file to use in METAL:
ext="final_collection"
generatefile<-function(extension,cohort){
sink(file=paste0(progdir,"/metal_script_",cohort,"_5pc_diff_dens"))
cat(paste0("#metal_script_",cohort,"_5pc_diff_dens

#THIS SCRIPT EXECUTES AN ANALYSIS OF THE ",cohort," FAMILY AND CASE-CONTROL GROUPS

#LOAD THE INPUT FILES

# === DESCRIBE AND PROCESS THE FIRST INPUT FILE ===
MARKER SNP
ALLELE RefAllele NonRefAllele
EFFECT BETA
STDERR SE
SCHEME STDERR
"))
if(cohort=="EAS"){
cat(paste0("PROCESS ",resdir,"meta_file_fam_",cohort,"_newqc_1_dens.tbl
OUTFILE \'",resdir,"/METAANALYSIS_",cohort,"\'
ANALYZE

QUIT"))
}
if(cohort!="EAS"){
cat(paste0("PROCESS ",resdir,"metal_results_",cohort,"_5pc_diff_dens.tbl
#All files are of the same format so can process immediately:
PROCESS ",resdir,"/meta_file_fam_",cohort,"_newqc_1_dens.tbl

OUTFILE \'/data1/ji3x/gwas_",extension,"/META/METAANALYSIS_",cohort,"_dens\'
ANALYZE

QUIT"))
}
sink()
}
lapply(cohorts1,generatefile,extension="final_collection")


#finally the file to run the metal script:

generatescript<-function(extension, cohort){
sink(file=paste0(progdir,"/run_metal_",cohort,"_5pc_diff_dens.sh"))
cat(paste0("#!/bin/bash
#run_metal_",cohort,"_5pc_diff_dens.sh

metal metal_script_",cohort,"_5pc_diff_dens

#Currently can't get the results to output to where i'd like them to,
#so I am moving here:
mv METAANALYSIS1.TBL METAANALYSIS_",cohort,"_dens.TBL
mv METAANALYSIS1.TBL.info METAANALYSIS_",cohort,"_dens.TBL.info

mv METAANALYSIS_",cohort,"_dens.TBL ",resdir,"
mv METAANALYSIS_",cohort,"_dens.TBL.info ",resdir,"
"))
sink()
system(paste0("chmod a=rwx ",progdir,"/run_metal_",cohort,"_5pc_diff_dens.sh"))
}
lapply(cohorts1,generatescript,extension="final_collection")

