#pre_meta_qc.R

#this script generates shell scripts to perform association tests for each different cohort, directly from the VCF file 
#and taking into account the uncertainty in the genotype imputation.


extension="final_collection"
cohorts=c("AMR","EUR","AFR","FIN")
vcfpath="/nv/vol185/MEGA/release4/IMPUTED_TOPMED/results_filtered/"
dobbypath="/scratch/ji3x/final_collection_gwas/vcf/"
outpath<-"/scratch/ji3x/final_collection_gwas/META/"

#generate a list of all unrelated cases and controls:
genlist<-function(cohort){
s<-system(paste0("tabix -H ",vcfpath,cohort,"/unrelateds/chr22.filter_maf_gt_0.005_rsq_gt_0.8.unrelateds.dose.vcf.gz"), intern=T)
s<-s[[length(s)]]
s<-strsplit(s,split="\t")
s<-s[[1]]
s<-s[10:length(s)]
write.table(s, file=paste0(dobbypath,cohort,"/samples.txt"), quote=F, row.names=F, col.names=F)
s<-data.frame(id=s)
return(s)
}
unrel<-lapply(cohorts, genlist)
unrel<-do.call("rbind", unrel)
write.table(unrel,file=paste0(dobbypath,"/unrelated"),quote=F, col.names=F, row.names=F)

#and all controls:
pheno<-read.table(file=paste0("/nv/vol185/MEGA/mega_genotyped/release4/mega_b37_clean_pheno_genotypedOnly.txt"),as.is=T)
controls<-pheno[pheno[,7]==1,]
cont<-unrel[unrel$id %in% controls$V2,]
write.table(cont,file=paste0(dobbypath,"unrelated_cont"),quote=F, col.names=F, row.names=F)


#Using the PCA files generated by Cassie:

#combine with PCA files:
getpcs<-function(cohort){
pcs<-read.table(file=paste0("/nv/vol185/MEGA/release4/pca/mega_pca_b37_pruned_unrelated_",cohort,"_pca_proj_onto_controls.sscore"), header=F, as.is=T)
pcs<-pcs[,c(1,2,6:10)]
colnames(pcs)<-c("id1","id",paste0("PC",1:5))
r<-read.table(file=paste0(dobbypath,cohort,"/samples.txt"), as.is=T)
rownames(pcs)<-pcs$id
out<-pcs[r$V1,]
rownames(out)<-out$id
out<-out[,c("id",paste0("PC",1:5))]
return(out)
}

pcsall<-lapply(cohorts, getpcs)
names(pcsall)<-cohorts

#get the phenotype data:
pheno<-read.table(file=paste0("/nv/vol185/MEGA/mega_genotyped/release4/mega_b37_clean_pheno_genotypedOnly.txt"),as.is=T)
pheno<-pheno[,c("V3","V6","V7")]
colnames(pheno)<-c("id","sex","t1d")
pheno$t1d<-ifelse(pheno$t1d==2,1,ifelse(pheno$t1d==1,0,NA))

getphen<-function(cohort){
r<-read.table(file=paste0(dobbypath,cohort,"/samples.txt"), as.is=T)
if (length(table(pcsall[[cohort]]$id %in% pheno$id))>1){
message(paste0("ERROR! CHECK IDS ARE ALL PRESENT IN THE PCS FILE - UNDERSCORE ISSUES - ", cohort))
}
all<-merge(pcsall[[cohort]],pheno,by="id")
rownames(all)<-all$id
all<-all[r$V1,]
colnames(all)[1]<-"ID_1"
all$ID_2<-all$ID_1
all$missing<-0
all<-all[c("ID_1","ID_2","missing","t1d","sex","PC1","PC2","PC3","PC4","PC5")]
dummy<-c("0","0","0","B","D","C","C","C","C","C")
for (i in 1:9){
all[,i]<-as.character(all[,i])
}
all<-rbind(dummy, all)
write.table(all, file=paste0(dobbypath,"/",cohort,"/samps_snptest"), sep=" ", col.names=T, row.names=F, quote=F)
}
invisible(lapply(cohorts,getphen))

#Now lets generate shell scripts that will test for association for each cohort:
ext="final_collection"
dothescripts<-function(cohort, chr){
sink(file=paste0("~/programs/",ext,"/META/snptest_scripts/",cohort,"_chr",chr))
cat(paste0("#!/bin/bash
#SBATCH --time=5:00:00
#SBATCH -A rich_immunochip_impute
#SBATCH -p standard
#SBATCH -n 1


module load gcc\n"))
cat(paste0("~/software/snptest_v2.5.4-beta3_linux_x86_64_static/snptest_v2.5.4-beta3 -data ",
vcfpath,"/",cohort,"/unrelateds/chr",chr,".filter_maf_gt_0.005_rsq_gt_0.8.unrelateds.dose.vcf.gz ",dobbypath,"/",cohort,"/samps_snptest -filetype vcf -include_samples ",dobbypath,"/",cohort,
"/samples.txt -genotype_field GP -pheno t1d -cov_all_continuous -frequentist 1 -method newml -o ",outpath,"/",
cohort,"/chr_",chr))
sink()
system(paste0("sbatch ~/programs/",ext,"/META/snptest_scripts/",cohort,"_chr",chr))
}


lapply(c(1:22),dothescripts,cohort="EUR")
lapply(c(1:22),dothescripts,cohort="FIN")
lapply(c(1:22),dothescripts,cohort="AMR")
lapply(c(1:22),dothescripts,cohort="AFR")



