---
title: "QC comparing genome studio exports for MEGA"
author: "Cassie Robertson"
date: "`r Sys.Date()`"
output: html_document 
---
		
# Set up
```{r setup, include=FALSE}
		knitr::opts_chunk$set(
		fig.width=12, fig.height=8, fig.path='figures/',
		echo=FALSE, 
		warning=FALSE, 
		message=FALSE)
library(dplyr)
```


### Compare allele frequencies across exports
```{r allele_frequency}
plotAF = function(label) {
	d1 = read.table(paste0("testing_af_diff_",label,".assoc"), header=TRUE)
	plot(d1$F_A, d1$F_U, ylim=c(0,1), xlim=c(0,1), main=label)
	abline(a=0, b=1, col="red")
	abline(h=0.5)
}
plotAF("mega_cbr_vs_mega_main")
plotAF("mega_jhu_vs_mega_main")
plotAF("mega_additions_vs_mega_main")
```

### Compare SNP Mendelian error rates across exports (based on inferred relationships)
```{r mendel_error_by_snp}
showError = function(label) {
	cat(label)
	d = read.table(paste0("testing_mendelError_",label,"bySNP.txt"), header=TRUE)
	cat("Error rate in PO:")
	print(summary(d$Err_InHomPO))
	#hist(d$Err_InHomPO)
	cat("Error rate in trios:")
	print(summary(d$Err_InHetTrio))
	#hist(d$Err_InHetTrio)
}
showError("mega_main")
showError("mega_jhu")
showError("mega_cbr")
showError("mega_additions")
```


### Compare relationship error rates within exports (how many pedigree errors?) 
```{r mendelerror_by_export}
map = read.table("genome_studio_export_map.txt", header=TRUE)
bysample = read.table("testing_MendelErrorsbySample.txt", header=TRUE)
m_bysample = merge(bysample, map, by="IID")
cat("Error rate in PO:")
m_bysample %>%
		group_by(Export) %>%
		summarise(mean = mean(Err_MIp), median = median(Err_MIp), max = max(Err_MIp))
cat("Error rate in trios:")
m_bysample %>%
		group_by(Export) %>%
		summarise(mean = mean(Err_MIt), median = median(Err_MIt), max = max(Err_MIt))
```

### Relationship errors in families from multiple exports
```{r relerrors}
d = read.table("testing_RelErrors.kin", header=TRUE)

cat("Families spanning exports:") 
keeplist = read.table("families_in_multiple_exports_iids.txt", header=FALSE)
names(keeplist) <- c("FID", "IID", "Export")
table(keeplist$FID, keeplist$Export)
row.names(keeplist) = keeplist$IID

d$Export1 = keeplist[d$ID1,"Export"]
d$Export2 = keeplist[d$ID2,"Export"]

cat("Rel errors:")
d[,c("FID","Export1","ID1","Export2","ID2","Phi","InfType", "Error")]

```
